version: '3.8'

services:
  app:
    build: .
    container_name: app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=123456
      - DB_DATABASE=testing
      - refresh_key=this is refresh_key
      - expirein=1m
    ports:
      - '4000:4000'
    networks:
      - app-network

  db:
    image: mysql:8.4
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: testing
    ports:
      - '3306:3306'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
