name: Docker Build and Deploy

on:
    pull_request:
        branches:
            - main # Trigger this workflow on push to the 'main' branch

jobs:
    build:
        runs-on: ubuntu-latest # Use the latest version of Ubuntu

        steps:
            # Step 1: Checkout the code
            - name: Checkout code
              uses: actions/checkout@v4

            # Step 2: Set up Node.js (or your specific environment)
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '16' # Specify the Node.js version (if needed)

            # Step 3: Install dependencies
            - name: Install dependencies
              run: npm install

            # Step 4: Run tests
            - name: Run tests
              run: npm test # Replace with the appropriate command to run your tests

            # Step 5: Set up Docker
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            # Step 6: Log in to Docker Hub
            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }} # Use secret for Docker Hub username
                  password: ${{ secrets.DOCKER_HUB_TOKEN }} # Use secret for Docker Hub password or access token

            # Step 7: Build Docker image from Dockerfile
            - name: Build Docker Image
              run: |
                  docker build -t my-app -f Dockerfile.prod .

            # Step 8: Push the Docker image to Docker Hub
            - name: Push Docker Image
              run: |
                  docker tag my-app ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:${{ github.event.pull_request.number }}
                  docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:${{ github.event.pull_request.number }}
